name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CI: true
    steps:
      - uses: actions/checkout@v5
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:8
      - run: sbt clean scalafmtSbtCheck scalafmtCheckAll +package
