name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check Sonatype token
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          curl -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" \
            -H "Accept: application/json" -sSf \
            https://ossrh-staging-api.central.sonatype.com/service/local/staging/profiles >/dev/null

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
#          ref: master
          ref: workflow/release

      - name: Check tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo $TAG
          echo Branches
          git branch
          echo Tags
          git tag
          if test $(git rev-parse workflow/release) = $(git rev-parse $TAG); then
            echo "master and $TAG are the same"
          else
            echo "master and $TAG are different"
          fi
          exit 1

      - uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:17

      - name: Release to Maven Central
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: sbt ci-release

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          gh release create $TAG --title $TAG --generate-notes
