name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    if: ${{ !github.event.release.draft && !github.event.release.prerelease }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Target commitish: ${{ github.event.release.target_commitish }}"

      - run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Validating tag: $TAG"

          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format: '$TAG'. Expected: vMAJOR.MINOR.PATCH (e.g. v1.2.3)" >&2
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:17

      - name: Check Sonatype token
        run: |
          curl -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" \
            -H "Accept: application/json" -sSf \
            https://s01.oss.sonatype.org/service/local/status >/dev/null
          sbt -v 'sonatypeProfiles'
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Release to Maven Central
        run: sbt ci-release
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
