name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check Sonatype token
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          curl -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" \
            -H "Accept: application/json" -sSf \
            https://ossrh-staging-api.central.sonatype.com/service/local/staging/profiles >/dev/null

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: master

      - name: Check tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if [ "$(git rev-parse "${{ github.event.repository.default_branch }}")" != "$(git rev-parse "$TAG"^{})" ]; then
            echo "master and $TAG should be the same at the moment of the release" >&2
            exit 1
          fi

      - uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:17

      - name: Release to Maven Central
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: sbt ci-release

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          gh release create $TAG --title $TAG --generate-notes --latest
