name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    secrets: inherit
    uses: h8io/.github/.github/workflows/release.yaml@master
    with:
      java-version: 8

