name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    secrets: inherit
    uses: h8io/gha/workflows/test.yaml@v2
    with:
      java-version: 8
